class Autogenerated {
  int? statusCode;
  CompanyObj? companyObj;

  Autogenerated({this.statusCode, this.companyObj});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    companyObj = json['CompanyObj'] != null
        ? new CompanyObj.fromJson(json['CompanyObj'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    if (this.companyObj != null) {
      data['CompanyObj'] = this.companyObj!.toJson();
    }
    return data;
  }
}

class CompanyObj {
  String? name;
  String? email;
  String? mobile;
  List<String>? domainName;
  int? activeFlag;
  String? bgColor;
  String? image;
  List<String>? images;
  String? address;
  String? url;

  CompanyObj(
      {this.name,
      this.email,
      this.mobile,
      this.domainName,
      this.activeFlag,
      this.bgColor,
      this.image,
      this.images,
      this.address,
      this.url});

  CompanyObj.fromJson(Map<String, dynamic> json) {
    name = json['Name'];
    email = json['Email'];
    mobile = json['mobile'];
    domainName = json['domainName'].cast<String>();
    activeFlag = json['activeFlag'];
    bgColor = json['bgColor'];
    image = json['image'];
    images = json['images'].cast<String>();
    address = json['address'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Name'] = this.name;
    data['Email'] = this.email;
    data['mobile'] = this.mobile;
    data['domainName'] = this.domainName;
    data['activeFlag'] = this.activeFlag;
    data['bgColor'] = this.bgColor;
    data['image'] = this.image;
    data['images'] = this.images;
    data['address'] = this.address;
    data['url'] = this.url;
    return data;
  }
}
