import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:sevika/screens/homescreen.dart';
import '../models/domain.dart';

 class carouseldata extends ChangeNotifier {
  Autogenerated? _data;

  Autogenerated? get data => _data;

   setData(Autogenerated? newData) {
    _data = newData;
    notifyListeners();
  }
}